# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-05-31T22:22:23+00:00

from __future__ import annotations

from typing import Union, Annotated

import uvicorn
from fastapi import FastAPI, Depends

from app.config import Config
from app.depends import get_qna_service
from app.models import HTTPValidationError, Request, Response

from app.service.qna import QnaService

app = FastAPI(
    title='Assistant API',
    version='0.1.0',
)


@app.post(
    '/assist',
    response_model=Response,
    responses={'422': {'model': HTTPValidationError}},
    tags=['default'],
)
def assist_assist_post(
        body: Request,
        qna_service: Annotated[QnaService, Depends(get_qna_service)],
) -> Union[Response, HTTPValidationError]:
    answer, links = qna_service.query_answer(body.query)
    return Response(text=answer, links=links)


if __name__ == '__main__':
    uvicorn.run("main:app", port=Config.port, reload=False, log_level="debug")
