# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-05-31T22:22:23+00:00

from __future__ import annotations

import os
from typing import Union, Annotated

from fastapi import FastAPI, Depends

from .depends import get_qna_service
from .models import HTTPValidationError, Request, Response

from .service.qna import QnaService

from dotenv import load_dotenv

load_dotenv(".env", verbose=True)
print(os.getcwd())

app = FastAPI(
    title='Assistant API',
    version='0.1.0',
)


@app.post(
    '/assist',
    response_model=Response,
    responses={'422': {'model': HTTPValidationError}},
    tags=['default'],
)
def assist_assist_post(
        body: Request,
        qna_service: Annotated[QnaService, Depends(get_qna_service)],
) -> Union[Response, HTTPValidationError]:
    answer, links = qna_service.query_answer(body.query)
    return Response(text=answer, links=links)
